readme completion and all the images/screenshots required by it
IBM/continuous-learning-with-watson-ml-and-db2 pull request #2
Opened 2018-10-16 18:27 UTC by sanjeevghimire

2018-10-16 20:55 UTC, dolph requested changes

2018-10-16 20:55 UTC, dolph commented on README.md
> +4. [Create DB2 warehouse on cloud and add the connection to Watson Studio](#3-create-db2-warehouse-on-cloud-and-add-the-connection-to-watson-studio)
The number on the left says 4, the number in the link says #3, so this will be a broken link

2018-10-16 20:55 UTC, dolph commented on README.md
> +4. [Create DB2 warehouse on cloud and add the connection to Watson Studio](#3-create-db2-warehouse-on-cloud-and-add-the-connection-to-watson-studio)
from here down they're all at least off by one

2018-10-16 20:55 UTC, dolph commented on README.md
> +###1. Clone the rep
repo

2018-10-16 20:55 UTC, dolph commented on README.md
> +If you do not already have a IBM Cloud account, [sign up for Bluemix](https://console.bluemix.net/registration).
a IBM -> an IBM

2018-10-16 20:55 UTC, dolph commented on README.md
> +> you might have to create `Cloud Object Storage` if you don't already have one.
I'd explicitly add this to the directions before creating the watson studio project

2018-10-16 20:55 UTC, dolph commented on README.md
> +Select the uploaded data file (.csv). At the top right, click Refine. We don't need to manipulate the data, so simply click the "run" button labeled with a ▶ icon at the top right. The data flow outp
Use backticks around literals like `.csv`

2018-10-17 16:56 UTC, rhagarty submitted a review, later dismissed
some text issues

2018-10-17 18:07 UTC, rhagarty requested changes
some text change suggestions

2018-10-17 18:07 UTC, rhagarty commented on README.md
> +In this code pattern, we will use IBM Watson Machine Learning and Watson Studio, which allows data scientists and analysts to quickly build and prototype models, to monitor deployments, and to learn
"... as more data becomes available."
"Continuous Learning enables machine ..."
"re-train"
"by the user or other data sources"

2018-10-17 18:07 UTC, rhagarty commented on README.md
>  In this code pattern, we’ll solve a problem for the City of Chicago using the Model Builder to model building violations. We’ll predict which buildings are most likely to fail buildings inspections.
"most likely to fail an inspection."
"for the city and for" (lowercase city)

2018-10-17 18:07 UTC, rhagarty commented on README.md
> +If you do not already have an IBM Cloud account, [sign up for Bluemix](https://console.bluemix.net/registration) and login to your IBM cloud account.
use IBM Cloud instead of Bluemix

2018-10-17 18:07 UTC, rhagarty commented on README.md
> +First you will need to create `Object Storage` if you don't already have one. From the catalog, search for `object storage`, select `Object Storage` service, choose the `lite` plan and click `create`
"need to create an Object Storage service if you ..."

2018-10-17 18:07 UTC, rhagarty commented on README.md
> +Create a new Project by clicking the `New Project` link, choose `Complete` , give it a name and click create.
remove space before second comma

2018-10-17 18:07 UTC, rhagarty commented on README.md
> +In Watson Studio, go to your project and select `Assets` tab. And from the right navigation panel, click `Browse` to upload your source data that will be used by the machine learning service to creat
".. to your project and select the Assets tab. From the right ... "

2018-10-17 18:07 UTC, rhagarty commented on README.md
> +Select the uploaded data file (`.csv`). At the top right, click Refine. We don't need to manipulate the data, so simply click the "run" button labeled with a ▶ icon at the top right. The data flow ou
is "Refine" an option or button? If so, add tick marks around it. Same with 'Save' and 'Run`.

2018-10-17 18:07 UTC, rhagarty commented on README.md
> +From the catalog search for `DB2 Warehouse on Cloud` and create one using the appropriate plan.
"From the IBM Cloud catalog, search for ... "

2018-10-17 18:07 UTC, rhagarty commented on README.md
> +Once the service is created, create new credentials from `Service Credentials` from left navigation panel. Make sure to save the credentials for upcoming steps.
"create new credentials by selecting the Service Credentials option in the left navigation panel"

2018-10-17 18:07 UTC, rhagarty commented on README.md
> +Then from Watson Studio project that you have created earlier, got to `+ Add to Project` and choose `Connection`
"From the Watson Studio project that you created earlier, ..."

2018-10-17 18:07 UTC, rhagarty commented on README.md
> +Select `Db2 Warehouse` from the available options to connect to Db2 warehouse you created earlier.
"... to connect to the DB2 warehouse service you created earlier"

2018-10-17 18:07 UTC, rhagarty commented on README.md
> +And configure the connection based on the DB2 credentials you saved earlier.
"Configure the ..."

2018-10-17 18:07 UTC, rhagarty commented on README.md
> +and create the service using `lite` plan.
probably shouldn't continue a sentence after a diagram. 

"Create the service ..."

2018-10-17 18:07 UTC, rhagarty commented on README.md
> +and create the service using `lite` plan.
same as comment above

2018-10-17 18:07 UTC, rhagarty commented on README.md
> +Similarly like in Step 5, Add the machine learning service you just created to your Watson Studio project.
"Similar to the previous step,  add the machine ..."

2018-10-17 18:07 UTC, rhagarty commented on README.md
> +From your Watson Studio project, Assets tab, select `+ New Watson Machine Learning Model`
"From the Assets tab of your Watson Studio project, select ..."
Add tick marks around "Assets"

2018-10-17 18:07 UTC, rhagarty commented on README.md
> +Provide a name, choose the `Machine Learning` and `Apache Spark` instance that you added to your project, choose `Model Builder` for model type and `Manual` so that you can prepare your own data and
To make more readable, put into item list, or add commas. Something like:
"Provide a name, choose the `Machine Learning` and `Apache Spark` instance that you added to your project, choose `Model Builder` for model type, choose `Manual` so that you can prepare your own data, then click `Create`"

2018-10-17 18:07 UTC, rhagarty commented on README.md
> +Once the data is loaded, choose the `INSPECTION_STATUS` as the column to predict for new set of data and `All` for feature columns. We will be using `Binary Classification`. Add Estiimators by clicki
change case in "YOu"

2018-10-17 18:07 UTC, rhagarty commented on README.md
> +Once the training and evaluation is done, you can choose the best performed one and click `Save`.
"... you can choose the one that performed the best and then click `Save`."

2018-10-17 18:07 UTC, rhagarty commented on README.md
> +* Add the spark service you added to watson studio project
"... to your Watson Studio project"

2018-10-17 18:07 UTC, rhagarty commented on README.md
> +* Choose `areaUnderPR` (performance metric of the model) and select the threshold as 0.8. This means if the performance is under 0.8, the model needs to be retrained using all the source data and new
"re-trained"

2018-10-17 18:07 UTC, rhagarty commented on README.md
> +* Add the connection by selecting `Select Feedback Reference Data` and select the DB2 connection that you have created in the steps earlier.
"... that you previously created."

2018-10-17 18:07 UTC, rhagarty commented on README.md
> +* You can also see list of evaluations that has been completed and see how the model has been continuously learning
"... see the list of evaluation that have completed and ..."

2018-10-17 18:07 UTC, rhagarty commented on README.md
> +* You can upload new feedback data repeatedly from the provided data [Chicago building inspection data by month 2017](building_inspection_data_by_month_2017.zip)  so that the model cointinuously lear
remove extra space after "zip)"
"continuously"

2018-10-17 18:07 UTC, rhagarty commented on README.md
> +* Select the model, and select `Deployments` tab. click `+ Add Deployment` to add a new deployment,
"then select the `Deployments` tab."
Uppercase 'Click"

2018-10-17 18:07 UTC, rhagarty commented on README.md
> +To test the API, either you can use `curl` commands or through programming to access the API. You can also go to the `Test` tab and provide new set of data to evaluate the inspection status.
"You can access and test the API programmatically, or use `curl` commands. "
"... and provide a new set ..."

2018-10-17 18:07 UTC, rhagarty commented on README.md
> +The result of the evaluation is shown at the right part of the page with horizontal graph.
"The result of the evaluation is shown in a horizontal graph located on the right side of the page."

2018-10-17 18:07 UTC, rhagarty commented on README.md
> +If the evaluation gives an error as below, you need to upgrade the `Machine Learning` service instance to `Standard` plan
"If the evaluation gives an error (as shown below), you need ..."
"service instance to the `Standard`.."

2018-10-17 18:29 UTC, rhagarty requested changes
2 small fixes

2018-10-17 18:29 UTC, rhagarty commented on README.md
> +In this code pattern, we will use IBM Watson Machine Learning and Watson Studio, which allows data scientists and analysts to quickly build and prototype models, to monitor deployments, and to learn
"by the user or other data sources"

2018-10-17 18:29 UTC, rhagarty commented on README.md
> +* You can also see list of evaluations that has been completed and see how the model has been continuously learning
looks like you missed this one

2018-10-17 18:45 UTC, rhagarty approved these changes

2018-10-17 18:49 UTC, merged