Data upload
IBM/continuous-learning-with-watson-ml-and-db2 pull request #4
Opened 2018-10-24 22:19 UTC by sanjeevghimire

* added steps to upload source data
* added steps to create tables that are organized by row
* readme changes
* flow diagram changes

2018-10-24 23:03 UTC, rhagarty requested changes

2018-10-24 23:03 UTC, rhagarty commented on README.md
> +5. Feedback data is uploaded to the feedback table in DB2 warehouse.
you should be consistent - is it  "DB2", or "Db2" (2 lines up)

2018-10-24 23:03 UTC, rhagarty commented on README.md
> +4. [Create and load data to DB2 warehouse](#4-create-and-load-data-to-db2-warehouse)
think "into" would be a better term here

2018-10-25 01:57 UTC, sanjeevghimire commented
done

2018-10-25 03:12 UTC, rhagarty approved these changes

2018-10-25 03:12 UTC, merged

2018-10-25 14:11 UTC, roger-e-sanders commented on README.md
> +5. Feedback data is uploaded to the feedback table in DB2 warehouse.
It is Db2. You should also refer to the product as "Db2 Warehouse on Cloud". Db2 Warehouse is a completely different product.